
/*	BD MESSAGERIE		*/

CREATE TABLE `ADRESSE` (
  `idADRESSE` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`idADRESSE`));


CREATE TABLE `PERSONNE` (
  `idPERSONNE` VARCHAR(80) NOT NULL,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  PRIMARY KEY (`idPERSONNE`),
  CONSTRAINT `fk_PERSONNE_ADRESSE`
    FOREIGN KEY (`idPERSONNE`)
    REFERENCES `ADRESSE` (`idADRESSE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
    

CREATE TABLE `LISTE` (
  `idLISTE` VARCHAR(80) NOT NULL,
  `libelle` VARCHAR(120) NULL,
  PRIMARY KEY (`idLISTE`),
  CONSTRAINT `fk_LISTE_ADRESSE`
    FOREIGN KEY (`idLISTE`)
    REFERENCES `ADRESSE` (`idADRESSE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
    
    
CREATE TABLE `MESSAGE` (
  `idMESSAGE` INT NOT NULL AUTO_INCREMENT,
  `sentdate` DATETIME NOT NULL,
  `subject` VARCHAR(200) NULL,
  `body` TEXT(65000) NULL,
  `sender` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`idMESSAGE`),
  CONSTRAINT `fk_MESSAGE_ADRESSE_sender`
	  FOREIGN KEY (`sender`)
	  REFERENCES `ADRESSE` (`idADRESSE`)
	  ON DELETE NO ACTION
	  ON UPDATE NO ACTION);
  

CREATE TABLE `DESTINATAIRE` (
  `ADRESSE_ID` VARCHAR(80) NOT NULL,
  `MESSAGE_ID` INT NOT NULL,
  PRIMARY KEY (`ADRESSE_ID`, `MESSAGE_ID`),
  CONSTRAINT `fk_DESTINATAIRE_idADRESSE`
    FOREIGN KEY (`ADRESSE_ID`)
    REFERENCES `ADRESSE` (`idADRESSE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DESTINATAIRE_idMESSAGE`
    FOREIGN KEY (`MESSAGE_ID`)
    REFERENCES `MESSAGE` (`idMESSAGE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
    
CREATE TABLE `DESTINATAIRE_COPIE` (
  `ADRESSE_ID` VARCHAR(80) NOT NULL,
  `MESSAGE_ID` INT NOT NULL,
  PRIMARY KEY (`ADRESSE_ID`, `MESSAGE_ID`),
  CONSTRAINT `fk_DESTINATAIRE_COPIE_idADRESSE`
    FOREIGN KEY (`ADRESSE_ID`)
    REFERENCES `ADRESSE` (`idADRESSE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DESTINATAIRE_COPIE_idMESSAGE`
    FOREIGN KEY (`MESSAGE_ID`)
    REFERENCES `MESSAGE` (`idMESSAGE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


CREATE TABLE `TRANSFERT` (
  `ADRESSE_ID` VARCHAR(80) NOT NULL,
  `MESSAGE_ID` INT NOT NULL,
  PRIMARY KEY (`ADRESSE_ID`, `MESSAGE_ID`),
  CONSTRAINT `fk_TRANSFERT_idADRESSE`
    FOREIGN KEY (`ADRESSE_ID`)
    REFERENCES `ADRESSE` (`idADRESSE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TRANSFERT_idMESSAGE`
    FOREIGN KEY (`MESSAGE_ID`)
    REFERENCES `MESSAGE` (`idMESSAGE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


CREATE TABLE `FICHIER` (
  `idFICHIER` INT NOT NULL AUTO_INCREMENT,
  `filetype` VARCHAR(8) NULL,
  `filename` VARCHAR(120) NULL,
  `filepath` VARCHAR(300) NOT NULL,
  `messageID` INT NOT NULL,
  PRIMARY KEY (`idFICHIER`),
  CONSTRAINT `fk_FICHIER_MESSAGE_ID`
    FOREIGN KEY (`messageID`)
    REFERENCES `MESSAGE` (`idMESSAGE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


CREATE TABLE `FONCTION` (
  `idFONCTION` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`idFONCTION`),
  UNIQUE (`title`));


CREATE TABLE `PERSONNE_FONCTION` (
  `idPERSONNE_FONCTION` INT NOT NULL AUTO_INCREMENT,
  `PERSONNE_ID` VARCHAR(80) NOT NULL,
  `FONCTION_ID` INT NOT NULL,
  `startdate` DATE NULL,
  `enddate` DATE NULL,
  PRIMARY KEY (`idPERSONNE_FONCTION`),
  CONSTRAINT `fk_PERS_FONCT_idPERSONNE`
    FOREIGN KEY (`PERSONNE_ID`)
    REFERENCES `PERSONNE` (`idPERSONNE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PERS_FONCT_idFONCTION`
    FOREIGN KEY (`FONCTION_ID`)
    REFERENCES `FONCTION` (`idFONCTION`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
    
    
CREATE TABLE `RATTACHEMENT` (
  `idRATTACHEMENT` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`idRATTACHEMENT`),
  UNIQUE (`title`));
  
  CREATE TABLE `PERSONNE_RATTACHEMENT` (
  `idPERSONNE_RATTACHEMENT` INT NOT NULL AUTO_INCREMENT,
  `PERSONNE_ID` VARCHAR(80) NOT NULL,
  `RATTACHEMENT_ID` INT NOT NULL,
  `startdate` DATE NULL,
  `enddate` DATE NULL,
  PRIMARY KEY (`idPERSONNE_RATTACHEMENT`),
  CONSTRAINT `fk_PERS_RATTACH_idPERSONNE`
    FOREIGN KEY (`PERSONNE_ID`)
    REFERENCES `PERSONNE` (`idPERSONNE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PERS_RATTACH_idRATTACHEMENT`
    FOREIGN KEY (`RATTACHEMENT_ID`)
    REFERENCES `RATTACHEMENT` (`idRATTACHEMENT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
    
    CREATE TABLE `LISTE_RATTACHEMENT` (
  `idLISTE_RATTACHEMENT` INT NOT NULL AUTO_INCREMENT,
  `LISTE_ID` VARCHAR(80) NOT NULL,
  `RATTACHEMENT_ID` INT NOT NULL,
  `startdate` DATE NULL,
  `enddate` DATE NULL,
  PRIMARY KEY (`idLISTE_RATTACHEMENT`),
  CONSTRAINT `fk_LISTE_RATTACH_idLISTE`
    FOREIGN KEY (`LISTE_ID`)
    REFERENCES `LISTE` (`idLISTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LISTE_RATTACH_idRATTACHEMENT`
    FOREIGN KEY (`RATTACHEMENT_ID`)
    REFERENCES `RATTACHEMENT` (`idRATTACHEMENT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


CREATE TABLE `MESSAGE_REPLY` (
  `MESSAGE_ID` INT NOT NULL,
  `MESSAGE_REPLY_ID` INT NOT NULL,
  PRIMARY KEY (`MESSAGE_ID`, `MESSAGE_REPLY_ID`),
  CONSTRAINT `fk_MESSAGE_idMESSAGE`
    FOREIGN KEY (`MESSAGE_ID`)
    REFERENCES `MESSAGE` (`idMESSAGE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MESSAGE_REPLY_idMESSAGE`
    FOREIGN KEY (`MESSAGE_REPLY_ID`)
    REFERENCES `MESSAGE` (`idMESSAGE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
